name: Upload package to TestPyPi and PyPi

# Publish when new tag is published
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Installs and upgrades pip, installs other dependencies and packages"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine build dtw-python numpy pandas PyWavelets scipy matplotlib

      - name: "Run unittests"
        run: python3 -m unittest discover tests/

      - name: Build package
        run: python3 -m build --wheel

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          TWINE_REPOSITORY: testpypi

      # Upload to PyPi
      - name: Build and Upload to PyPi
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
